# Generated by Django 4.0.6 on 2022-07-23 05:56

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_sign_up_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sign_up_type',
            field=models.CharField(max_length=12, verbose_name='sign up type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.IntegerField(verbose_name='Otp code')),
                ('otp_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
